### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by sacredMonster** [TrySound/postcss-value-parser#36]
Hello,
My project uses webpack@3.10.0 and I am seeing the below error when I run webpack -p command to build my project. 
```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./stylesheets/main.scss
Module build failed: TypeError: Cannot read property 'length' of undefined
    at module.exports (..\node_modules\postcss-value-parser\lib\unit.js:7:23)
    at ..\node_modules\css-loader\node_modules\postcss-minify-gradients\dist\index.js:65:65
    at Array.forEach (native)
    at ..\node_modules\css-loader\node_modules\postcss-minify-gradients\dist\index.js:60:22
```
Here is my webpack.config.js:
```
module: [
     {
        test: /\.scss$/,
        include: APP_DIR,
        loaders: ['style-loader', 'css-loader', 'sass-loader'],
      },
```
I have a potential fix in place in **unit.js** which removes the above error:
```
module.exports = function (value) {
    var pos = 0;
    var length = Object.prototype.toString(value) === '[object Array]'
        ? value.length
        : 0;
...
}
```
Do you think this is a valid fix? If yes, I can send a PR for this..
Thanks..

**Comment by MatellioRahul** [comment]
need this fixed soon.

**Comment by evilebottnawi** [comment]
Please provide example code what throw error

**Comment by MatellioRahul** [comment]
can you please fix the unit.js file it raises error for value not defined.
code causing the problem
var length = value.length;

code fix
var length = value ? value.length : 0;

**Comment by evilebottnawi** [comment]
@MatellioRahul https://github.com/TrySound/postcss-value-parser/issues/36#issuecomment-427306805

**Comment by tp00012x** [comment]
@sacredMonster I had this issue because i was doing `@import` inside my css files. You should import your global css files inside `index.js`
